import { deepFreeze } from "../utils/deepFreeze.mjs";

const PROJECT_IMAGE_FORMAT = "png";
const projectTitles = [
  "Random Meal Generator",
  "2022 Mood Calendar",
  "Flow Field",
  "Aim Trainer",
  "User Profile Design",
  "Pokedex",
  "James Bond Tribute Page",
  "",
  "This or That (cats)",
  "",
  "",
  "",
  "Password Generator",
  "Contact Page Design",
  "",
  "Clock",
  "Testimonial Design",
  "Typing Speed Test",
  "Send Love Button",
  "",
  "",
  "Tricky Cookie",
  "Background Animations",
  "Hover Board",
  "Reviews Design",
  "",
  "Line Through Effect",
  "",
  "Event KeyCodes And KPS",
  "Animated Navigation",
  "New Year Countdown",
  "Text to Life",
  "",
  "",
  "Image Reflection",
  "",
  "Panda Eye Follow",
  "3D Background Boxes",
  "",
  "",
  "",
  "Verify Account UI",
  "Rotated Nav Animation",
  "",
  "",
  "Image Password Strength",
  "Expanding Cards",
  "Content Placeholder",
  "Theme Toggler",
  "Infinite Scrolling",
  "",
  "",
  "",
  "Rotation Slideshow",
  "",
  "Digital Block Clock",
  "Become a Millionaire",
  "",
  "Direction Aware Hover Effect",
  "",
  "Live User Filter",
  "",
  "",
  "",
  "",
  "Moving Hamburger Animation",
  "",
  "",
  "Dad Jokes",
  "",
  "",
  "Instagram Image Feed",
  "Form Validation",
  "",
  "",
  "",
  "",
  "",
  "",
  "Steps",
  "Drink Water",
  "Random Picker Visualizer",
  "Youtube Video Suggestions UI",
  "",
  "",
  "",
  "",
  "Blurry Loading",
  "Rain Drop",
  "",
  "",
  "",
  "Incrementing Counter",
  "",
  "",
  "Waves",
  "",
  "FAQ"
];

const projectsInfo = {};
projectTitles.forEach((title, i) => {
  if (!title) return;
  const id = String(i + 1).padStart(3, '0');
  projectsInfo[id] = {
    id,
    title: `${title} - #${id}`,
    projectLink: `./Projects/Florin Pop 100Days100Projects/${id} - ${title}`,
    imageLink: `./src/assets/images/${id}.${PROJECT_IMAGE_FORMAT}`,
  }
})
deepFreeze(projectsInfo);

export { projectsInfo };
