const CANVAS_WIDTH = 1000;
const CANVAS_HEIGHT = 600;
const CANVAS_BACKGROUND_COLOR = "#f6f6f6";
const CANVAS_TARGET_COLOR = "#222";

export { CANVAS_WIDTH, CANVAS_HEIGHT, CANVAS_BACKGROUND_COLOR, CANVAS_TARGET_COLOR };
